### ISSUE TITLE
Check copyright and licensing

### ISSUE THREAD

**Issue by rzr** [adoptware/pinball-table-gnu#2]
Would  it be good to relocate debian/copyright file to COPYRIGHT ?

Please list any emilia pinball contributor here

cc: @sergiomb2 @c30zD

**Comment by rzr** [comment]
Does anyone is in contact with  author:

* Ben Asselstine <benasselstine(a)hushmail.com>

**Comment by sergiomb2** [comment]
From https://github.com/sergiomb2/pinball/blob/master/License.txt

https://github.com/rzr/pinball-table-gnu/blob/master/data/gnu/README

**Comment by rzr** [comment]
I tried to email him, but you know 2020 interwebz is not the way it used to be...

ps: I added CI bot to check debian packaging

If anyone here is interested to maintain debian packaging, let me know I can mentor you.

cc: @henqvist

**Comment by sergiomb2** [comment]
> If anyone here is interested to maintain debian packaging, let me know I can mentor you.

I'm not , thank you , I already have a lot of packages to maintain on Fedora and on RPMFusion and a lot of other free and open projects

**Comment by rzr** [comment]
Proper copyright should look like this:

https://github.com/rzr/pinball-table-hurd/blob/master/debian/copyright

Do you any other similar format for this kind of info, I'd like to have it outside debian folder ?

I am trying to reach @BenAsselstine any clue ?

https://mastodon.social/@rzr/104092423857027574

**Comment by rzr** [comment]
This issue can be solved (It was checked by debian in #3) 

But feel free to comment this ticket.

I am wondering if a generic standardized copyright format exits
in this case debian/copyright should be translated to it ?

I remember I asked about this to @SoftwareHeritage at #Ow2Con2020 
but I not sure this format exists yet.

More to come about this project at:

https://purl.org/rzr/pinball
