### ISSUE TITLE
Publish to debian

### ISSUE THREAD

**Issue by rzr** [adoptware/pinball-table-gnu#3]
Relate-to: https://github.com/rzr/pinball-table-hurd/issues/5
Debian-Bug: https://bugs.debian.net/961930

**Comment by rzr** [comment]
Update: https://mentors.debian.net/package/pinball-table-gnu

**Comment by rzr** [comment]
Update:

https://ftp-master.debian.org/new/pinball-table-gnu_0.0.20200601-1.html

**Comment by sergiomb2** [comment]
Hi, I hope everything is fine with you
I think here is one of our disagreements , for what I understand , you want pinball be package in many packages one main package and one package for each table . And I want pack all in one package to give much less work . 
As having 2 , 3 or 4 repos is in my opinion a waste of time . 
If I already have little time for this project, and I have to waste time dividing it, without getting something tangible, it is something I will not do, TBH

**Comment by rzr** [comment]
hi @sergiomb2 , thanks for your comment

Let's follow the discussion at:
https://github.com/rzr/pinball/issues/4

**Comment by rzr** [comment]
It's in debian now::

https://tracker.debian.org/pkg/pinball-table-gnu

Any interest to RPM it as well ?

More to come:

https://purl.org/rzr/pinball
